### PR TITLE
[FIX] Dart-sass 1.33+ slash-div

### PR DESCRIPTION
**Pull request by mrleblanc101**

### CODE REVIEW

**Comment by martinbroos** [comment]
Thanks for this. Would be nice if this could be released.

**Comment by miguelcobain** [comment]
@waldemarfm could you please merge and release this? 🙏

**Comment by waldemarfm** [comment]
I apologize for the delay. I honestly had no idea this would be used by anyone. I’ll take a look at the contributions and come up with a release schedule soon!

**Comment by waldemarfm** [comment]
Please check the latest major version. Should be fully compatible with latest module syntax and uses built-in modules. Dart Sass 1.33+ is required (because of math.div).

**Comment by miguelcobain** [comment]
Thank you!

**Pull request closed without merging**
